
[34m[1mwandb[39m[22m: [33mWARNING[39m Symlinked 4 files into the W&B run directory, call wandb.save again to sync new files.
Vocab size:  103
Vocab size:  103
Epoch: 0/199 Phase: train Loss: 3.6065 (3.5932) Acc: 0.0052 (0.0000) Rec comedy: 0.0000 (nan):   0%|     | 3/1717 [00:00<07:51,  3.64it/s]
0.366337
[1447, 8259, 699, 5886, 65184, 2396, 31583, 1191, 37.6, 284, 23025, 3398, 6012, 30723, 2644, 6336, 1004, 1220, 2262, 2043, 313, 620, 1487, 1228, 2888, 925, 1041, 1123, 1106, 2972, 867, 736, 2735, 816, 213.0, 1994, 2646]








































Epoch: 0/199 Phase: train Loss: 3.5292 (3.4445) Acc: 0.0303 (0.1562) Rec comedy: 0.0690 (nan):  17%|â–Œ  | 293/1717 [01:21<06:37,  3.58it/s]
Traceback (most recent call last):
  File "train.py", line 358, in <module>
    wandb,
  File "train.py", line 97, in train
    outputs = model(seqs, lengths)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/konst/ml-utils/training/tagger_text/model.py", line 128, in forward
    x,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py", line 683, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED